### ISSUE TITLE
Error when compiling clmp with igraph being built from source 

### ISSUE THREAD

**Issue by 0ldM4j0r** [PoonLab/clmp#17]
I built `igraph` from source, but when running ` R CMD INSTALL clmp` I get the following error message:
```
Error: package or namespace load failed for ‘clmp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/tng92/R/x86_64-pc-linux-gnu-library/3.4/clmp/libs/clmp.so':
  libigraph.so.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/tng92/R/x86_64-pc-linux-gnu-library/3.4/clmp’
```
I managed to reproduce this error on @gtng92 machine. On the bright side the fix is simple, running `sudo ldconfig` fixes the problem.

**Comment by ArtPoon** [comment]
Apparently this is a known issue with Ubuntu, and not related to Kaphi.
https://lists.nongnu.org/archive/html/igraph-help/2015-02/msg00063.html
