### ISSUE TITLE
mac install fix

### ISSUE THREAD

**Issue by antoine4ucsd** [PoonLab/clmp#18]
For Mac users, you may have to edit the Makevars file before running 'R CMD INSTALL clmp'
and replace -lfl by -ll as follow:
PKG_LIBS = -ligraph -L/usr/local/lib -L/opt/local/lib -lgsl -ll

It works fine with me.
thank you for this great tool!

**Comment by ArtPoon** [comment]
Thanks for the feedback!  I'll test your proposed edit and update `INSTALL.md` accordingly.
