### ISSUE TITLE
warning ? ConditionNumber

### ISSUE THREAD

**Issue by thednainus** [PoonLab/clmp#19]
Hello!!

I am using the `clmp` in the a mac OS X Yosemite (10.10.5) and R version 3.3.3.

Running the command `clmp(tree, nrates = 2)` I get the following warning for some of my trees:
Example1: `ConditionNumber: maximal condition number 9.01e+12 reached. maxEW=7.75e-04,minEW=7.80e-17,maxdiagC=4.37e-04,mindiagC=2.48e-09`

Example2: `ConditionNumber: maximal condition number 9.01e+12 reached. maxEW=8.21e-03,minEW=7.58e-16,maxdiagC=1.00e-02,mindiagC=4.72e-16`

I get similar message if I use `nrates = 3`.
I am treating it as a warning, because the analysis does not stop.  Should I be worried about it?
And please let me know if you need more information.

**Comment by ArtPoon** [comment]
Hi @thednainus, you're seeing warning messages associated with CMA-ES optimization, which was implemented by @cma-es.  This message means that the algorithm failed the check on the ratio of the largest and smallest eigenvalues of the covariance matrix -- it's a warning that the resulting optimization may be numerically unstable.  Based on the documentation for CMA-ES, we can expect to encounter condition numbers up to 10^10 and the method should be okay "for condition numbers up to 10^14".  This is just what I've been able to gather from a quick survey of the literature.  

My suggestion would be to run some tests on simulated data resembling your problem (if possible) or comparing the *clmp* estimates against other methods as a sanity check.

**Comment by ArtPoon** [comment]
@thednainus, would you be able to send me the tree you are trying to fit so that I can try to reproduce the warning message and diagnose?

**Comment by ArtPoon** [comment]
Hi @thednainus, thanks for the tree received via e-mail.  I was able to reproduce the warning message and noticed that the transition rate matrix `Q` contained an entry near the default upper bound (`1e5`):
```R
ConditionNumber: maximal condition number 9.01e+12 reached. maxEW=3.42e-07,minEW=3.19e-20,maxdiagC=3.96e-07,mindiagC=1.74e-16
log likelihood for 2 state model is 60.987984
rates: 0.000000 1229.092212 
Q: [    *   951.120775 ]
   [ 9999.978081   *    ]
```

So I re-ran the analysis with the upper bounds increased to `1e6` and obtained clean run and very different parameter estimates:
```R
log likelihood for 2 state model is 59.110403
rates: 22.339844 129.637513 
Q: [    *   48.944301 ]
   [ 14.944518   *    ]
```

So for some reason, the optimization algorithm was getting trapped at the upper bound for `Q`.
On the other hand, the cluster assignments returned by the function were `1` for all branches, which implies to me that this tree does not support multiple rate classes.
